sudo: false
language: node_js
node_js:
  - "6.9.1"
install:
  - npm run install-deps
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
after_script:
  - npm run coverage
  - npm run firebase deploy --token "$FIREBASE_TOKEN";
git:
  depth: 10
