sudo: false
language: node_js
node_js:
  - "5.0.0"
  - "5.1.0"
install:
  - npm run install-deps
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
after_script:
  - npm run coverage
  - if [ -n "$TRAVIS_TAG" ];
    then npm run firebase deploy --token $FIREBASE_TOKEN;
git:
  depth: 10
